# Generated by Django 4.2.7 on 2026-02-04 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Текст совета",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("motivation", "💪 Мотивация"),
                            ("comfort", "🤗 Утешение"),
                            ("inspiration", "✨ Вдохновение"),
                            ("wisdom", "🧠 Мудрость"),
                        ],
                        default="motivation",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Совет",
                "verbose_name_plural": "Советы",
            },
        ),
    ]
